version: '3'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: inventory
      POSTGRES_USER: zsz13
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - ./database_dump.sql:/docker-entrypoint-initdb.d/database_dump.sql
      - pg_data:/var/lib/postgresql/data
    restart: always

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"


  web:
    build: .
    command: ["bash", "-c", "while !</dev/tcp/db/5432; do sleep 1; done; sleep 30; cd drfhalyksite; \
              python3 manage.py migrate; celery -A drfhalyksite worker -l info; celery -A drfhalyksite beat -l info; \
              celery -A drfhalyksite flower; \
              uvicorn drfhalyksite.asgi:application --host 0.0.0.0 --reload --log-level info",]

    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq
    restart: always
    environment:
      - DB_HOST=db

  nginx:
    image: nginx:1.18
    ports:
      - "1080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./drfhalyksite/static:/app/static
    depends_on:
      - web
    restart: always

volumes:
  pg_data:

