version: '3'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: inventory
      POSTGRES_USER: zsz13
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - ./database_dump.sql:/docker-entrypoint-initdb.d/database_dump.sql
      - pg_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis
    hostname: redis

  worker:
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - .:/app
    links:
      - redis
    depends_on:
      - redis

  flower:
    build:
      context: .
    hostname: flower
    entrypoint: celery
    command: -A celery_app.app flower
    volumes:
      - .:/app
    links:
      - redis
    depends_on:
      - redis
    ports:
    -  "5555:5555"

  web:
    build: .
    command: ["bash", "-c", "while !</dev/tcp/db/5432; do sleep 1; done; cd drfhalyksite; python3 manage.py migrate; \
              gunicorn -c gunicorn_config.py drfhalyksite.wsgi:application 0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always
    environment:
      - DB_HOST=db

  nginx:
    image: nginx:1.18
    ports:
      - "1080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./drfhalyksite/static:/app/static
    depends_on:
      - web
    restart: always

volumes:
  pg_data:

